### ISSUE TITLE
Connecting video to layer render function

### ISSUE THREAD

**Issue by xariusdesai** [dnass/svelte-canvas#2]
Hi, I'm pretty new to svelte.

I've been trying to get a video element to play in the svelte-canvas render function.

I've seen how to do it with vanilla JS and canvas [here](https://stackoverflow.com/a/50506098) but I'm unsure how to translate it to make the video reactive for the render function to update.

I've got a REPL going [here](https://svelte.dev/repl/f6199e1ae4c3417f944b28af1f9f7190?version=3.24.1) to show the basics of what I'm trying to do, any help would be appreciated

**Comment by dnass** [comment]
If you bind to the video's `currentTime` property and reference that variable in the render function, it'll trigger a render when the video plays. [Here's](https://svelte.dev/repl/4f47c661c498494b8f863db0435acacd?version=3.24.1) a working example.

**Comment by xariusdesai** [comment]
Ah! thats very simple 👍 

Obviously without testing it, do you know if there would be any kind of performance drops with this method over using requestAnimationFrame? I'm planning on doing some ml5 bodypix estimation to my video (not the one in the repl)

**Comment by dnass** [comment]
You shouldn't see much difference in performance compared to a vanilla JS implementation — the main render loop in the Canvas component uses rAF, so the layer's render function won't be called more than once per frame, no matter how often the value of currentTime changes. That said, this library is pretty new and I haven't tested it in a scenario like this, so if you do run into issues let me know and hopefully we can find a fix.

**Comment by matias-kovero** [comment]
@dnass 
Not sure if something has changed on svelte as just started using it, but the given example on earlier comment is not working anymore. Will give an error:
`render must be a function (tps:/unpkg.com/svelte-canvas@0.6.1/src/Layer.svelte)`

This same error is present when trying to reference the `t` variable in render loop like:
```js
$: render = $t && (({ context, width, height }) => {
    // Will throw: render must be a function
  });
```
I believe it's because giving `$t` on the function. Why this does not work any more I don't know.

On the other examples where t is used inside the render loop, it will work just fine.
```js
$: render = ({ context, width, height }) => {
    context.fillStyle = `hsl(${$t / 40}, 100%, 50%)`;
    // This will work fine, as $t is referenced inside it will trigger the renders.
  };
```

However there might be cases where you don't really need to use the `$t` and currently the render won't keep rendering if I don't use the $t parameter.

Ps. This same issue is on the DVD example, how ever the [repl](https://svelte.dev/repl/34d79dea30b8428590b8cb76221ca1d4?version=3.38.2) of it works?
But the identical code on a fresh sveltekit project will cause the error as above.

**Comment by dnass** [comment]
Huh, I'll try to figure out what's going on here — in the meantime you can definitely reference `$t` inside the render function to trigger the loop, even if you don't use it. For example:

```
$: render = ({ context, width, height }) => {
    $t;
    context.beginPath();
    // etc.
};
```
