### ISSUE TITLE
Safari performance

### ISSUE THREAD

**Issue by jokull** [dnass/svelte-canvas#25]
Not sure if this is svelte-canvas related but the DVD demo for example, goes to 100% cpu usage on Safari. It's fine in Firefox/Chrome. Does Safari just suck at canvas animations?

**Comment by dnass** [comment]
Hey, good catch. It looks like this is related to the use of `globalCompositeOperation = 'destination-in'` in the DVD demo. When I remove that line, the CPU usage falls and the FPS improves. Not something that can be fixed in the library — but that said, I'm not aware of any other Safari-specific perf issues, so hopefully this one is more of an edge case.
