### ISSUE TITLE
Passing canvas width/height to Layer

### ISSUE THREAD

**Issue by samrat** [dnass/svelte-canvas#58]
Thanks for this library!

I'm trying to adapt the [resizable layer example](https://dnass.github.io/svelte-canvas/examples/resize) so that the squares drawn in the canvas are scaled up/down according to the size of the canvas. I'm trying to create a video editor timeline where I don't know before hand what the cavas dimensions will be.

I'm able to get the dimensions of a parent container containing the canvas(from the code below, I see them both in the console log output and in the `span`), but `ResizableLayer` doesn't seem get the updated `w` and `h` values once they are `bind`ed. 

I'm new to Svelte, so I'm probably missing something. Or, is there another way to get this kind of responsiveness?

```svelte
<script>
    import { Canvas, Layer } from "svelte-canvas";
    import ResizableLayer from "./ResizableLayer.svelte";

    let w, h;
    $: console.log("w", w, "h", h);
</script>

<div class="w-full h-full" bind:clientWidth={w} bind:clientHeight={h}>
    <span>{w}</span>
    <span>{h}</span>
    <Canvas layerEvents width={w} height={h}>
        <ResizableLayer
            initialBounds={{ x0: 0, y0: 0, x1: w, y1: h }}
            let:bounds
        >
            <Layer
                render={({ context, width, height }) => {
                    const { x0, y0, x1, y1 } = bounds;
                    context.globalAlpha = 0.9;
                    context.fillStyle = "tomato";
                    context.fillRect(x0, y0, x1 - x0, y1 - y0);
                    context.globalAlpha = 1;
                }}
            />
        </ResizableLayer>
    </Canvas>
</div>
```

**Comment by dnass** [comment]
Since [this line](https://github.com/dnass/svelte-canvas/blob/878577e2060f42b77c0dda835a27446ccef6eca8/src/routes/examples/resize/ResizableLayer.svelte#L11) uses `let` instead of `$:`, the value of `initialBounds` is only used when the component first mounts. You could change this to be reactive, but then the bounds will reset when the canvas is resized, which probably isn't the outcome you're looking for.

Another option would be to change `ResizableLayer`'s internal representation of its bounds to percentages instead of pixels. Then when the canvas dimensions change, the layers will scale while preserving their current proportions.
